//...
<tipo> <nome>[<tam>]{<val1>, ..., <valn>};	//Sintaxe de Inicialização
//...
int V1[5]{};					//Todos os valores como 0
int V2[5]{1,2,3,4,5};	//Valores conforme sequência
int V3[]{1,2,3,4,5};	//Tamanho do vetor implícito
//...
for (int i(0); i<5; i++) V1[i]=V2[i]+V3[i];	//Inicialização póstera
//...